Bootstrap: shub
From: vsoch/hello-world

%runscript
    exec echo "The runscript is the containers default runtime command!"

%files
    hello-kitty.txt        # copied to root of container

%environment
    VARIABLE=MEATBALLVALUE
    export VARIABLE

%labels
   AUTHOR vsochat@stanford.edu

%post
    apt-get update && apt-get -y install python3 git wget
    mkdir /data
    echo "The post section is where you can install, and configure your container."